## Linear Combination
### Use NumPy

$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 5 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 0 \\ 0 \\ 8 \end{bmatrix}$$
- Find <b>b</b> vector where $$b=3v_1+0v_2+0v_3$$
- Find <b>x</b> vector where $$x=-v_1+v_2-0.5v_3$$

In [1]:
import numpy as np
import sympy as sp

In [2]:
v1 = np.array([1,2,3])
v2 = np.array([3,5,1])
v3 = np.array([0,0,8])

In [3]:
b = 3*v1
x = -1*v1 + v2 - 0.5*v3
b.reshape(-1,1), x.reshape(-1,1)

(array([[3],
        [6],
        [9]]),
 array([[ 2.],
        [ 3.],
        [-6.]]))

## Vector Span
### Use Numpy (matrix inverse) and SymPy (rref)

#### Is $$v=\begin{bmatrix} 19 \\ 10 \\ -1 \end{bmatrix}$$ in the span of 
$$v_1=\begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix},
v_2=\begin{bmatrix} -5 \\ 0 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 1 \\ 7 \\ -4 \end{bmatrix}$$

In [4]:
v = np.array([19,10,-1])

In [5]:
a = np.array([[3,-5,1],
            [-1,0,7],
            [2,1,-4]])
print(np.linalg.solve(a,v)) 
print(np.matmul(np.linalg.inv(a),v.reshape(3,-1)))
# v is in the span of v1, v2, v3
# so the solution is a = 4, b = -1, c = 2

[ 4. -1.  2.]
[[ 4.]
 [-1.]
 [ 2.]]


In [6]:
a = sp.Matrix([[3,-5,1,19],
            [-1,0,7,10],
            [2,1,-4,-1]])
a.rref()
# v is in the span of v1, v2, v3
# so the solution is a = 4, b = -1, c = 2

(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]),
 (0, 1, 2))

## Vector Linear Independence
### Use rref and determinant
- Consider the following sets of vectors in R3. If the set is independent, prove it. 
- If the set is dependent, find a nontrivial linear combination of the vectors which is equal to 0.
    - {(2, 0, -3), (1, 1, 1), (1, 7, 2)}.
    - {(1, 2, -1), (4, 1, 3), (-10, 1, -11)}.

<b>Hint: we have to determine whether this implies that 𝒂=𝒃=𝒄=𝟎.</b>

In [7]:
a = sp.Matrix([[2,1,1],
            [0,1,7],
            [-3,1,2]])
a.rref()
# it is independent

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [8]:
a = sp.Matrix([[1,4,-10],
            [2,1,1],
            [-1,3,-11]])
a.rref()
# this vector is not independent

(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]),
 (0, 1))

In [9]:
# v3 = 2*v1+ -3*v2
# so a = 2, b = -3, c = -1

In [10]:
a = sp.Matrix([[1,4,-10,0],
            [2,1,1,0],
            [-1,3,-11,0]])
a.rref()
# this vector is not independent

(Matrix([
 [1, 0,  2, 0],
 [0, 1, -3, 0],
 [0, 0,  0, 0]]),
 (0, 1))

## Linear Transformation
### Ex.1

$$T=\begin{bmatrix} 1&2 \\ 3&7 \end{bmatrix}$$
- Write the linear transformation expression of this matrix. i.e. Linear functions of x,y. 
- Apply the transformation matrix <b>T</b> to the following vectors:
$$\begin{bmatrix} 1 \\ 0 \end{bmatrix},\begin{bmatrix} 0 \\ 1 \end{bmatrix} $$
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(1,0)</b>

In [11]:
# x + 2y
# 3x + 7y

In [12]:
T = np.array([[1,2],
            [3,7]])

In [13]:
v = np.array([1,0])
np.matmul(T,v)

array([1, 3])

In [14]:
v = np.array([0,1])
np.matmul(T,v)

array([2, 7])

In [15]:
np.linalg.solve(T,np.array([1,0]))

array([ 7., -3.])

### Ex.2
### For the expression $$T\begin{bmatrix} x \\ y \end{bmatrix}=\begin{bmatrix} x+y \\ y \end{bmatrix}$$
- Find the transformation matrix.
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(3,4)</b>

In [16]:
T = np.array([[1,1],
                [0,1]])
#np.linalg.solve(T,np.array([3,4])).reshape(-1,1)
np.linalg.inv(T)@np.array([3,4])

array([-1.,  4.])

## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [17]:
np.linalg.det(np.array([[3,8],
                        [4,6]]))

-14.000000000000004

In [18]:
np.linalg.det(np.array([[4,6],
                        [3,8]]))

14.000000000000004

In [19]:
np.linalg.det(np.array([[6,1,1],
                        [4,-2,5],
                        [2,8,7]]))

-306.0

In [20]:
np.linalg.det(np.array([[3,2,0,1],
                        [4,0,1,2],
                        [3,0,2,1],
                        [9,2,3,1]]))

24.000000000000004

## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [21]:
A = sp.Matrix([[1,2,4,4],
            [3,4,8,0]])
A.rref()
# rank is 2 cause we have just 2 pivot cols

(Matrix([
 [1, 0, 0, -8],
 [0, 1, 2,  6]]),
 (0, 1))

In [22]:
np.linalg.matrix_rank(np.array([[1,2,4,4],
            [3,4,8,0]]))

2

In [23]:
A = sp.Matrix([[1,2,3],
            [2,3,5],
            [3,4,7],
            [4,5,9]])
A.rref()
# rank is 2 cause we have just 2 pivot cols

(Matrix([
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 0],
 [0, 0, 0]]),
 (0, 1))

In [24]:
np.linalg.matrix_rank(np.array([[1,2,3],
            [2,3,5],
            [3,4,7],
            [4,5,9]]))

2

## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [25]:
np.linalg.inv(np.array([[3,8],
                        [4,6]]))

array([[-0.42857143,  0.57142857],
       [ 0.28571429, -0.21428571]])

In [26]:
np.linalg.inv(np.array([[4,6],
                        [3,8]]))

array([[ 0.57142857, -0.42857143],
       [-0.21428571,  0.28571429]])

In [32]:
np.linalg.inv(np.array([[6,1,1],
                        [4,-2,5],
                        [2,8,7]]))

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [33]:
np.linalg.inv(np.array([[3,2,0,1],
                        [4,0,1,2],
                        [3,0,2,1],
                        [9,2,3,1]]))

array([[-0.25      ,  0.25      , -0.5       ,  0.25      ],
       [ 0.66666667, -0.5       ,  0.5       , -0.16666667],
       [ 0.16666667, -0.5       ,  1.        , -0.16666667],
       [ 0.41666667,  0.25      ,  0.5       , -0.41666667]])