In [2]:
import numpy as np

### Practice some NumPy commands:
- Create 3 * 3 array.
- Check its shape.
- Select first row.
- Select 2nd column.
- Select the 2nd element in the third column.
- Create 2*2 from the first two elements of the first 2 rows and columns.
- Create single row vector.
- Create single column vector.

In [3]:
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [4]:
a.shape

(3, 3)

In [5]:
a[0]

array([1, 2, 3])

In [6]:
a[:,1]

array([2, 5, 8])

In [7]:
a[1,2]

6

In [8]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [9]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## System of linear equations:
- The following system of linear equations can be represented as <b>Ax=b</b>.
- Define matrix <b>A</b> and vector <b>b</b> as numpy arrays.
- Print them out.
1. $$3x-y=2$$ $$x=4 $$
$$$$
2. $$3x-2y=7$$  $$2x-2y=2$$
$$$$
3. $$2x-2y+z=7$$  $$x+y+z=2$$  $$3x-2y-z=3$$ 

In [19]:
A1 = np.array([[3,-1],
                [1,0]])
b1 = np.array([[2],[4]])
# or np.array([2,4])
A1,b1

(array([[ 3, -1],
        [ 1,  0]]),
 array([[2],
        [4]]))

In [20]:
A2 = np.array([[3,-2],
                [2,-2]])
b2 = np.array([[4],[2]])
# or np.array([2,4])
A2,b2

(array([[ 3, -2],
        [ 2, -2]]),
 array([[4],
        [2]]))

In [21]:
A3 = np.array([[2,-2,1],
            [1,1,1],
            [3,-2,-1]])
b3 = np.array([[7],[2],[3]])
# or np.array([2,4])
A3,b3

(array([[ 2, -2,  1],
        [ 1,  1,  1],
        [ 3, -2, -1]]),
 array([[7],
        [2],
        [3]]))

### Find a solution for the above systems of equations using:
<b>np.linalg.inv()</b>

In [32]:
inv1 = np.linalg.inv(A1)@b1

In [33]:
inv2 = np.linalg.inv(A2)@b2

In [34]:
inv3 = np.linalg.inv(A3)@b3

### Find a solution for the above systems of equations using:
<b>np.linalg.solve()</b>

In [35]:
np.linalg.solve(a=A3,b=b3)

array([[ 0.90909091],
       [-1.36363636],
       [ 2.45454545]])

## Using numpy arrays
- For the above systems of equations, multiply matrix <b>A</b> and vector <b>x</b> and make sure the result is <b>b</b>.

In [37]:
np.matmul(A1,inv1)

array([[2.],
       [4.]])

In [38]:
np.matmul(A2,inv2)

array([[4.],
       [2.]])

In [39]:
A3@inv3

array([[7.],
       [2.],
       [3.]])

## Vector Norms

### Calculate in paper then confirm your results using numpy linalg.norm().
- Calculate L1, L2, Lmax norms for the following vectors:
$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 3 \\ 1 \\ 3 \end{bmatrix}$$
- Calculate L3 norm for the vector
$$v_3=\begin{bmatrix} 2 \\  3 \\ 4 \end{bmatrix}$$

In [40]:
v1 = np.array([1,2,3])
v2 = np.array([3,3,1,3])
v3 = np.array([2,3,4])

In [41]:
np.linalg.norm(v1,1),np.linalg.norm(v1,2)

(6.0, 3.7416573867739413)

In [42]:
np.linalg.norm(v2,1),np.linalg.norm(v2,2)

(10.0, 5.291502622129181)

In [43]:
np.linalg.norm(v3,3)

4.626065009182741

## Calculate using numpy only.
### Calculate L1, L2, L3, and Lmax for the following vectors:
$$v_1=\begin{bmatrix} 5 \\ 6 \end{bmatrix},
v_2=\begin{bmatrix} 4 \\ 3 \\ 2 \end{bmatrix},
v_3=\begin{bmatrix} 4 \\ 3 \\ 2 \\ 8 \\ 9 \end{bmatrix}$$

In [44]:
v1 = np.array([5,6])
v2 = np.array([4,3,2])
v3 = np.array([4,3,2,8,9])

In [45]:
np.linalg.norm(v1,1),np.linalg.norm(v1,2), np.linalg.norm(v1,3), np.linalg.norm(v1,np.Inf)

(11.0, 7.810249675906654, 6.986368027818105, 6.0)

In [46]:
np.linalg.norm(v2,1),np.linalg.norm(v2,2), np.linalg.norm(v2,3), np.linalg.norm(v2,np.Inf)

(9.0, 5.385164807134504, 4.626065009182741, 4.0)

In [47]:
np.linalg.norm(v3,1),np.linalg.norm(v3,2), np.linalg.norm(v3,3), np.linalg.norm(v3,np.Inf)

(26.0, 13.19090595827292, 11.02473771449733, 9.0)

## Dot Product

### Calculate in paper then confirm your results using numpy.
#### Calculate the dot product of the following vectors:
$$v_1=\begin{bmatrix} 2 \\ -1 \\ 5 \\ 0 \end{bmatrix} and
v_2=\begin{bmatrix} 4 \\ -3 \\ 1 \\ -1 \end{bmatrix}$$
#### Calculate the dot product of the following vectors and explain the result:
$$v_1=\begin{bmatrix} 3 \\ 2 \\ -1 \\ 4 \end{bmatrix} and
v_2=\begin{bmatrix} 1 \\ -1 \\ 1 \\ 0 \end{bmatrix} $$ 

In [48]:
v1 = np.array([2,-1,5,0])
v2 = np.array([4,-3,1,-1])
np.dot(v1,v2)

16

In [49]:
v1 = np.array([3,2,-1,4])
v2 = np.array([1,-1,1,0])
np.dot(v1,v2)

0

## Calculate in paper then confirm your results using numpy.
### Create two vectors in 2, 3, and 4 dimensions.
### Perform vector addition, subtraction, and dot product of these vectors.

In [58]:
a = np.full((2,1), 2)
b = np.full((2,1), 3)
c = np.full((3,1), 4)
d = np.full((3,1), 5)
e = np.full((4,1), 4)
f = np.full((4,1), 4)

In [59]:
a

array([[2],
       [2]])

In [60]:
np.add(a,b)

array([[5],
       [5]])

In [61]:
np.subtract(d,c)

array([[1],
       [1],
       [1]])

In [62]:
np.dot(e.reshape(-1),f.reshape(-1))

64

## Matrix Operations

## Calculate in paper then confirm your results using numpy.
### Matrix Multiplication AB then Transpose the result.
$$A=\begin{bmatrix} 3&1&0 \\ 2&1&2 \end{bmatrix}, B=\begin{bmatrix} 1&3 \\ 2&5 \\ -1&3 \end{bmatrix}$$
$$A=\begin{bmatrix} 1&0&3 \\ 4&5&-1 \\ 0&0&2  \end{bmatrix}, B=\begin{bmatrix} 1\\2\\5 \end{bmatrix}$$

In [69]:
A = np.array([[3,1,0],
            [2,1,2]])
B = np.array([[1,3],
                [2,5],
                [-1,3]])
np.matmul(A,B), np.matmul(A,B).T

(array([[ 5, 14],
        [ 2, 17]]),
 array([[ 5,  2],
        [14, 17]]))

In [70]:
A = np.array([[1,0,3],
            [4,5,-1],
            [0,0,2]])
B = np.array([[1],[2],[5]])
np.matmul(A,B), np.matmul(A,B).T

(array([[16],
        [ 9],
        [10]]),
 array([[16,  9, 10]]))

## Different Types of Matrices
### Create 3 by 3 and 4 by 4 identity matrices 

In [65]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Create a diagonal matrix contains [2,4,5,11] numbers in its diagonal.

In [67]:
np.diag([2,4,5,11])

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 11]])

### Create a 5 by 5 scalar matrix of number 7

In [99]:
7*np.eye(5)

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

### Using SymPy get the rref of the following matrices

In [71]:
import sympy as sp

In [90]:
A = sp.Matrix([[1,0,1,3],
        [2,3,4,7],
        [-1,-3,-3,-4]])
A.rref()

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]),
 (0, 1))

In [91]:
A = sp.Matrix([[1,0,1,3],
        [2,3,4,7],
        [-1,-3,-3,-4]])
A.rref()


(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]),
 (0, 1))

In [92]:
A = sp.Matrix([[1,1,1],
        [1,2,2],
        [1,2,3]])
A.rref()


(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [93]:
A = sp.Matrix([[1,2,3],
        [2,-1,1],
        [3,0,-1]])
A.rref()


(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [95]:
A = sp.Matrix([[1,0,1,3],
        [0,1,2/3,1/3],
        [0,0,0,0]])
A.rref()


(Matrix([
 [1, 0,                 1,                 3],
 [0, 1, 0.666666666666667, 0.333333333333333],
 [0, 0,                 0,                 0]]),
 (0, 1))

In [80]:
A = sp.Matrix([[1,0,0],
        [0,1,0],
        [0,0,1],
        ])
A.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [83]:
A = sp.Matrix([[1,2,3],
        [2,-1,1],
        [3,0,-1]])
A.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

#### Find the solution of the following system of linear equation using SymPy Matrix rref()

1. $$x+y+z=6$$  $$x+2y+2z=9$$  $$x+2y+3z=10$$ 
$$$$
2. $$x+2y+3z=9$$  $$2x-y+z=8$$  $$3x-z=3$$ 

In [84]:
A = sp.Matrix([[1,1,1,6],
        [1,2,2,9],
        [1,2,3,10]])
A.rref()
# solution is x = 3, y = 2, z = 1

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]),
 (0, 1, 2))

In [85]:
A = sp.Matrix([[1,2,3,9],
        [2,-1,1,8],
        [3,0,-1,3]])
A.rref()
# solution is x = 2, y = -1, z = 3

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]),
 (0, 1, 2))

#### Find the solution of the following system of linear equation 
- Using SymPy Matrix rref()

1. $$x-2y=1$$ $$3x-6y=11 $$
$$$$
2. $$x-2y=1$$ $$3x-6y=3 $$
$$$$
3. $$x+2y+3z=6$$  $$2x+5y+2z=4$$  $$6x-3y+z=2$$ 
$$$$
4. $$2x+4y-2z=2$$  $$4x+9y-3z=8$$  $$-2x-3y+7z=10$$ 

In [86]:
A = sp.Matrix([[1,-2,1],
        [3,-6,11]])
A.rref()
# there is no solution

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

In [87]:
A = sp.Matrix([[1,-2,1],
        [3,-6,3]])
A.rref()
# infinite number of solutions

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]),
 (0,))

In [88]:
A = sp.Matrix([[1,2,3,6],
        [2,5,2,4],
        [6,-3,1,2]])
A.rref()
# solution is x = 0, y = 0, z = 2

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]),
 (0, 1, 2))

In [89]:
A = sp.Matrix([[2,4,-2,2],
        [4,9,-3,8],
        [-2,-3,7,10]])
A.rref()
# solution is x = -1, y = 2, z = 2

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]),
 (0, 1, 2))