In [2]:
import numpy as np
import sympy as sp

In [3]:
# question 1
v = np.array([4,1])
w = np.array([-2,2])
v + w, v - w

(array([2, 3]), array([ 6, -1]))

In [4]:
# question 2
u = np.array([-0.6,0.8])
v = np.array([4,3])
w = np.array([1,2])
np.dot(u,v), np.dot(u,w),np.dot(u,(v+w)), np.dot(w,v)

(4.440892098500626e-16, 1.0, 1.0, 10)

In [5]:
# question 3
u = np.array([-0.6,0.8])
v = np.array([4,3])
w = np.array([1,2])

np.linalg.norm(u), np.linalg.norm(v), np.linalg.norm(w)

(1.0, 5.0, 2.23606797749979)

In [45]:
# question 4
v = np.array([1, 1.732])
w = np.array([1,0])
np.dot(v,w)


57.29577951308232

In [7]:
# question 4
v = np.array([2,2,-1])
w = np.array([2,-1,2])
np.dot(v,w)
# so they are prepinduclar

0

In [8]:
# question 5
a = np.array([[1,2,4],
             [-2,3,1],
             [-4,1,2]])
b = np.array([[2],[2],[3]])

c = np.array([[2,1,0,0],
             [1,2,1,0],
             [0,1,2,1],
             [0,0,1,2]])
d = np.array([[1],[1],[1],[2]])

np.matmul(a,b), np.matmul(c,d)

(array([[18],
        [ 5],
        [ 0]]),
 array([[3],
        [4],
        [5],
        [5]]))

In [9]:
# question 6
v = np.array([2,1])
w = np.array([1,2])

np.add(3*v,w)

array([7, 5])

In [10]:
# question 7
u = np.array([1,2,3])
v = np.array([-3,1,-2])
w =  np.array([2,-3,-1])
np.add(np.add(u,v),w), np.add(np.add(2*u,2*v),w)

(array([0, 0, 0]), array([-2,  3,  1]))

In [11]:
# question 7
a = sp.Matrix([[1,-3,2],
           [2,1,-3],
           [3,-2,-1]])
a.rref()

(Matrix([
 [1, 0, -1],
 [0, 1, -1],
 [0, 0,  0]]),
 (0, 1))

In [12]:
# question 8
a = sp.Matrix([[1,3,14],
           [2,1,8]])
a.rref()

(Matrix([
 [1, 0, 2],
 [0, 1, 4]]),
 (0, 1))

In [13]:
# question 9
A = np.array([[1,2],
              [3,5]])

B = np.array([[2,1],
              [-4,-3]])

np.linalg.inv(A), np.linalg.inv(B)

(array([[-5.,  2.],
        [ 3., -1.]]),
 array([[ 1.5,  0.5],
        [-2. , -1. ]]))

In [14]:
# question 10
a = sp.Matrix([[1,3,-2,5],
           [3,5,6,7],
           [2,4,3,8]])
a.rref()

(Matrix([
 [1, 0, 0, -15],
 [0, 1, 0,   8],
 [0, 0, 1,   2]]),
 (0, 1, 2))

there is a sloution for it

In [15]:
# question 11
a = sp.Matrix([[1,2,3],
           [-1,1,0],
           [1,1,2]])
a.rref()

(Matrix([
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 0]]),
 (0, 1))

these vectors are dependent because it has
just 2 pivots and the third vector is combination of them

In [16]:
# question 12
v = np.array([1,3,2,5])
np.linalg.norm(v,1),np.linalg.norm(v,2),np.linalg.norm(v,3),np.linalg.norm(v,4),np.linalg.norm(v,np.Inf) 

(11.0, 6.244997998398398, 5.4401218254147965, 5.185427592735, 5.0)

In [17]:
# question 13
a = sp.Matrix([[1,-1,8],
           [2,-2,16],
           [6,-1,3]])
a.rref()

(Matrix([
 [1, 0, -1],
 [0, 1, -9],
 [0, 0,  0]]),
 (0, 1))

a = -1 
b = -9

In [18]:
# question 14
a = sp.Matrix([[0,2,4],
           [0,0,1],
           [1,1,2]])
a.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

these vectors are linearly indendent
so u is not in the span of v and w

In [19]:
# question 15
a = sp.Matrix([[-4,10,6],
           [2,-5,3]])
a.rref()

(Matrix([
 [1, -5/2, 0],
 [0,    0, 1]]),
 (0, 2))

no solution

In [20]:
# question 16
# [1,0]
# [0 3]
# are just scaled

In [21]:
# question 17
# [3,0]
# [0 3]
# are just scaled

In [22]:
# question 18
# [1 0 0]
# [0 1 0]
# [0 0 -1]
# are just scaled 
# and change the direction of z


In [23]:
# question 19
# determent is zeros meaning collapsing space
# because the is no area or vloume for the matrix


In [24]:
# question 20
# because the is no area or vloume for the matrix
# and that means these vectors are dependent


In [25]:
# question 21
# because the is no area or vloume for the matrix
# and that means these vectors are dependent
# so I can't tell if it is rank 1 or 2
# because these vectors could be in 
# 1d space if just one was indepented
# or 2 2d space if 2 vectors are independent

In [26]:
# question 22
a = sp.Matrix([[1,2,4],
           [-2,3,1],
           [-4,1,2]])
a.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

it is rank 3 because we have 3 pivot columns
so they are independent

In [27]:
# question 23
a = np.array([[1,2,4],
           [-2,3,1],
           [-4,1,2]])
np.linalg.matrix_rank(a)

3

In [28]:
# question 24
a = sp.Matrix([[1,1,0],
           [-1,1,0],
           [0,0,1]])
a.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

these vector are independent
so they are spanning the whole 3d space
so they are orthogonal

In [29]:
# question 24
v = np.array([3,7,4])
np.linalg.solve(np.array([[1,1,0],
           [-1,1,0],
           [0,0,1]]),v)

array([-2.,  5.,  4.])

In [30]:
# question 25
a = sp.Matrix([[1,-1],
           [2,2]])
a.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [31]:
# question 25
# and we need to check the norms of the vectors
np.linalg.norm(np.array([1,2])),np.linalg.norm(np.array([-1,2])) 

(2.23606797749979, 2.23606797749979)

they are not unit vectors
so they are just orthogonal

In [32]:
# question 26
# doesn't change span

In [33]:
# question 27
# at least one if it is collapsing space

In [34]:
# question 28
# must have eign value represent how it scaled

In [35]:
# question 29
a = np.array([[1,4],
         [2,3]])
np.linalg.eig(a)

(array([-1.,  5.]),
 array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [44]:
# question 30
a = sp.Matrix([[-0.89442719,-4],
           [0.4472136,2]])
a.rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

here these vectors are differnet 
so we they are not the same

In [37]:
# question 31
# Helps in data visualization and speed up the learning algorithms.

In [38]:
# question 32
# Is the projection of the original data on the principal component axes.


In [39]:
# question 33
# The axes are orthonormal.

In [40]:
# question 34
# It can be applied directly to the data matrix.

In [41]:
# question 35
# How much variance that each principal component preserves.