In [1]:
import numpy as np

In [2]:
A = np.array([[0,1,1], [1,0,1], [1,1,0]])
B = np.array([[0,2,3], [0,5,0], [7,0,0]])

In [3]:
np.multiply(A,B)

array([[0, 2, 3],
       [0, 0, 0],
       [7, 0, 0]])

In [4]:
np.add(A, B)

array([[0, 3, 4],
       [1, 5, 1],
       [8, 1, 0]])

In [5]:
A.T

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [10]:
A[1,:]

array([1, 0, 1])

In [12]:
a = A[:,2]
a

array([1, 1, 0])

In [13]:
b = B[2,]
b

array([7, 0, 0])

In [14]:
np.add(a, b)

array([8, 1, 0])