In [1]:
import numpy as np

In [2]:
np.linalg.det(np.array([[2,-1],
                        [3,-5]]))

-6.999999999999999

In [3]:
np.linalg.det(np.array([[1,3,-2],
                        [0,1,4],
                        [0,1,1]]))

-3.0000000000000004

In [4]:
np.linalg.det(np.array([[12,3,1],
                        [2,0,2],
                        [18,0,1]]))

102.00000000000004

In [6]:
# np.linalg.det(np.array([[1,2,3],
#                         [3,6,9]]))
# there is no det for non square matrix

In [7]:
np.linalg.inv(np.array([[2,-1],
                        [3,-5]]))

array([[ 0.71428571, -0.14285714],
       [ 0.42857143, -0.28571429]])

In [9]:
# np.linalg.inv(np.array([[1,2,3],
#                         [3,6,9]]))
# there is no inverse for this matrix cause it has no det

In [10]:
np.linalg.inv(np.array([[12,3,1],
                        [2,0,2],
                        [18,0,1]]))

array([[ 0.        , -0.02941176,  0.05882353],
       [ 0.33333333, -0.05882353, -0.21568627],
       [ 0.        ,  0.52941176, -0.05882353]])

In [12]:
np.linalg.inv(np.array([[1,1],
                        [1,-1]]))

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [13]:
np.linalg.inv(np.array([[1,2],
                        [3,5]]))

array([[-5.,  2.],
       [ 3., -1.]])

In [14]:
np.linalg.inv(np.array([[1,0,1],
                        [0,1,1],
                        [1,1,1]]))

array([[ 0., -1.,  1.],
       [-1.,  0.,  1.],
       [ 1.,  1., -1.]])