In [10]:
import numpy as np
import sympy as sp

In [39]:
A = sp.Matrix([[1,0,2,-5],
            [-2,5,0,11],
            [2,5,8,8]])
sp.Matrix(A.rref(pivots=False))
# these vectors are linearly dependent
# w is not a linear combination of v1,v2,v3 because it is linearly dependent 

Matrix([
[1, 0,   2, 0],
[0, 1, 4/5, 0],
[0, 0,   0, 1]])

In [30]:
# A = np.array(([[1,0,2],
#             [-2,5,0],
#             [2,5,8]]))
# v = np.array([-5,11,8])
# # 3*3 3*
# np.linalg.inv(A)
# #np.matmul(np.linalg.inv(A),v)

In [37]:
A = sp.Matrix([[1,1,0,0],
            [0,2,1,0],
            [1,2,2,0],
            [2,1,1,0]])
sp.Matrix(A.rref(pivots=False))

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 0]])

In [ ]:
# this matrix is not dependent
# which means it is just describe a 3d hyper plane in 4d space

In [40]:
T = sp.Matrix([[0,2,-1],
            [3,1,1],
            [0,-1,-2]])
A = np.array([[1,0,0],
            [0,1,0],
            [0,0,1]])
sp.Matrix(np.matmul(T,A))

Matrix([
[0,  2, -1],
[3,  1,  1],
[0, -1, -2]])

In [41]:
B = np.array([[1,0,0],
            [-1,1,0],
            [1,2,-1]])
sp.Matrix(np.dot(T,B))

Matrix([
[-3,  0,  1],
[ 3,  3, -1],
[-1, -5,  2]])

In [42]:
B = np.array([1,-1,1])
T@B

array([-3, 3, -1], dtype=object)

In [43]:
B = np.array([0,1,2])
np.matmul(T,B)

array([0, 3, -5], dtype=object)

In [44]:
B = np.array([0,0,-1])
np.matmul(T,B)

array([1, -1, 2], dtype=object)