In [1]:
import numpy as np

In [2]:
a = np.array([[0,1],
        [-2,-3]])

In [3]:
val, vec = np.linalg.eig(a)

In [5]:
# eign values
val

array([-1., -2.])

In [6]:
# eign vectors
vec

array([[ 0.70710678, -0.4472136 ],
       [-0.70710678,  0.89442719]])

In [7]:
a = np.array([[1,0],
        [0,2]])

In [8]:
val, vec = np.linalg.eig(a)

In [9]:
# eign values
val

array([1., 2.])

In [10]:
# eign vectors
vec

array([[1., 0.],
       [0., 1.]])